name: maeum_ga_gym_flutter
description: A new Flutter project.

publish_to: 'none'

version: 0.9.4+65

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.9
  go_router: ^12.1.1
  pedometer: ^4.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.9
  camera: ^0.10.5+9
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.8.0
  dio: ^5.4.0
  numberpicker: ^2.1.2
  flutter_secure_storage: ^9.0.0
  audioplayers: ^5.2.1
  syncfusion_flutter_gauges: ^24.2.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  datadog_flutter_plugin: ^2.4.0
  flutter_native_splash: ^2.3.10
  video_player: ^2.8.6
  cached_network_image: ^3.3.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/core_icon/
    - assets/image/sign_up_icon/
    - assets/image/bottom_navigation_bar_icon/
    - assets/image/home_icon/
    - assets/image/pose_icon/
    - assets/image/pose_icon/pose_exercise/
    - assets/image/self_care_icon/
    - assets/image/on_boarding_icon/
    - assets/sounds/metronome/
    - assets/sounds/timer/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/core_icon/splash_logo.png

  android_12:
    color: "#FFFFFF"
    image: assets/image/core_icon/splash_logo.png