List<Map<String, dynamic>> foodData = [
  {
    "image": 'assets/image/core_icon/logo.png',
    "foodName": '감자',
    'g': 215,
    'state': false,
    'category': ['전체', '채소'],
    'kcal': 460,
    'plate': '중접시',
    'unitValue': 1,
    'unit': '줄',
  },
  {
    "image": 'assets/image/core_icon/logo.png',
    "foodName": '감자',
    'g': 215,
    'state': false,
    'category': ['전체', '채소'],
    'kcal': 460,
    'plate': '중접시',
    'unitValue': 1,
    'unit': '줄',
  },
  {
    "image": 'assets/image/core_icon/logo.png',
    "foodName": '감자',
    'g': 215,
    'state': false,
    'category': ['전체', '채소'],
    'kcal': 460,
    'plate': '중접시',
    'unitValue': 1,
    'unit': '줄',
  },
  {
    "image": 'assets/image/core_icon/logo.png',
    "foodName": '감자',
    'g': 215,
    'state': false,
    'category': ['전체', '채소'],
    'kcal': 460,
    'plate': '중접시',
    'unitValue': 1,
    'unit': '줄',
  },
];
