// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvo8iZkSg6AJLjTYlBKaQWWd0KKanegww',
    appId: '1:807718817116:android:d76e0d139ef7cae054c599',
    messagingSenderId: '807718817116',
    projectId: 'maeumgagym-9c6b7',
    storageBucket: 'maeumgagym-9c6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_f4Q-_0ybmRRHU1HgKH9KbMr7J48vuQ',
    appId: '1:807718817116:ios:b6673dd4463d096f54c599',
    messagingSenderId: '807718817116',
    projectId: 'maeumgagym-9c6b7',
    storageBucket: 'maeumgagym-9c6b7.appspot.com',
    androidClientId: '807718817116-385334eq02niehojd69vsv0o89j6tind.apps.googleusercontent.com',
    iosClientId: '807718817116-ettu6iltusaecnfbtmkrnhopua9mfjcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.maeumgagymFlutter',
  );
}
