// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApgs53qdSpZL-sq0EROnBTjCEnnB-rBCU',
    appId: '1:878566104031:android:eef50bc125905a2577026a',
    messagingSenderId: '878566104031',
    projectId: 'maeumgagym-5a9df',
    storageBucket: 'maeumgagym-5a9df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkWNDJNbADNgGJkcXsYe-MPiR0czh1iI',
    appId: '1:878566104031:ios:64228e91223d5b9377026a',
    messagingSenderId: '878566104031',
    projectId: 'maeumgagym-5a9df',
    storageBucket: 'maeumgagym-5a9df.appspot.com',
    androidClientId: '878566104031-8ckir7id2invcvgoaqn54spcajr0k2d4.apps.googleusercontent.com',
    iosClientId: '878566104031-4n9ioco2dk32i2l9om1rhqb60hqir08k.apps.googleusercontent.com',
    iosBundleId: 'com.example.maeumgagymFlutter',
  );
}
