// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRFzYvfiyLhNoPPI_TXXvNWrKMnf84oU',
    appId: '1:455954015744:android:ba8ad91e5fce4c374f5ae5',
    messagingSenderId: '455954015744',
    projectId: 'maeumgagym-412003',
    storageBucket: 'maeumgagym-412003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKQ0Yfis7tKVZQ6gwuhdG_-egNWERGRNU',
    appId: '1:455954015744:ios:84a491f9bba2e6d74f5ae5',
    messagingSenderId: '455954015744',
    projectId: 'maeumgagym-412003',
    storageBucket: 'maeumgagym-412003.appspot.com',
    androidClientId: '455954015744-6cqekn2u23b1g6qqmvbokg35b9h9qskj.apps.googleusercontent.com',
    iosClientId: '455954015744-dpu84mkn5me1hdmfdnp0avvqerms327l.apps.googleusercontent.com',
    iosBundleId: 'com.example.maeumgagymFlutter',
  );
}
