///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Images {
  Images._();

  static const String arrowDown = 'assets/image/icons/arrow/down.png';
  static const String arrowLeft = 'assets/image/icons/arrow/left.png';
  static const String arrowRight = 'assets/image/icons/arrow/right.png';
  static const String arrowUp = 'assets/image/icons/arrow/up.png';
  static const String chevronDown = 'assets/image/icons/chevron/down.png';
  static const String chevronLeft = 'assets/image/icons/chevron/left.png';
  static const String chevronRight = 'assets/image/icons/chevron/right.png';
  static const String chevronUp = 'assets/image/icons/chevron/up.png';
  static const String editAdd = 'assets/image/icons/Edit/add.png';
  static const String editClose = 'assets/image/icons/Edit/close.png';
  static const String editMove = 'assets/image/icons/Edit/Move.png';
  static const String editPencil = 'assets/image/icons/Edit/pencil.png';
  static const String editRedo = 'assets/image/icons/Edit/Redo.png';
  static const String editRemoveMinus =
      'assets/image/icons/Edit/Remove_Minus.png';
  static const String editTrash = 'assets/image/icons/Edit/trash.png';
  static const String iconsArm = 'assets/image/icons/arm.png';
  static const String iconsArmFilled = 'assets/image/icons/arm-filled.png';
  static const String iconsBasket = 'assets/image/icons/basket.png';
  static const String iconsBell = 'assets/image/icons/bell.png';
  static const String iconsCalendar = 'assets/image/icons/calendar.png';
  static const String iconsCamera = 'assets/image/icons/camera.png';
  static const String iconsCart = 'assets/image/icons/cart.png';
  static const String iconsCartFilled = 'assets/image/icons/cart-filled.png';
  static const String iconsCheck = 'assets/image/icons/check.png';
  static const String iconsCheckCircle = 'assets/image/icons/check-circle.png';
  static const String iconsCheckCircleOutline =
      'assets/image/icons/check-circle-outline.png';
  static const String iconsCloseCircle = 'assets/image/icons/close-circle.png';
  static const String iconsDotsHorizontal =
      'assets/image/icons/dots-horizontal.png';
  static const String iconsDotsVertical =
      'assets/image/icons/dots-vertical.png';
  static const String iconsEarth = 'assets/image/icons/earth.png';
  static const String iconsEmail = 'assets/image/icons/email.png';
  static const String iconsEye = 'assets/image/icons/eye.png';
  static const String iconsEyeOff = 'assets/image/icons/eye-off.png';
  static const String iconsFacebook = 'assets/image/icons/facebook.png';
  static const String iconsFilter = 'assets/image/icons/filter.png';
  static const String iconsFlag = 'assets/image/icons/flag.png';
  static const String iconsHeart = 'assets/image/icons/heart.png';
  static const String iconsHeart1 = 'assets/image/icons/heart-1.png';
  static const String iconsHouse = 'assets/image/icons/house.png';
  static const String iconsHouseFilled = 'assets/image/icons/house_filled.png';
  static const String iconsImage = 'assets/image/icons/image.png';
  static const String iconsInbox = 'assets/image/icons/inbox.png';
  static const String iconsLink = 'assets/image/icons/link.png';
  static const String iconsLock = 'assets/image/icons/lock.png';
  static const String iconsMessage = 'assets/image/icons/message.png';
  static const String iconsNotDesignSysAddCircleIcon =
      'assets/image/icons_not_design_sys/add_circle_icon.svg';
  static const String iconsNotDesignSysAddWidgeticon =
      'assets/image/icons_not_design_sys/add_widget_icon.png';
  static const String iconsNotDesignSysCalculateIcon =
      'assets/image/icons_not_design_sys/calculate_icon.png';
  static const String iconsNotDesignSysCameraButtonIcon =
      'assets/image/icons_not_design_sys/camera_button_icon.png';
  static const String iconsNotDesignSysDietIcon =
      'assets/image/icons_not_design_sys/diet_icon.png';
  static const String iconsNotDesignSysDumbelIcon =
      'assets/image/icons_not_design_sys/dumbel_icon.png';
  static const String iconsNotDesignSysEmptyViewIcon =
      'assets/image/icons_not_design_sys/empty_view_icon.png';
  static const String iconsNotDesignSysProfileIcon =
      'assets/image/icons_not_design_sys/profile_icon.png';
  static const String iconsNotDesignSysRoutineIcon =
      'assets/image/icons_not_design_sys/routine_icon.png';
  static const String iconsNotDesignSysSparklingIcon =
      'assets/image/icons_not_design_sys/sparkling_icon.png';
  static const String iconsNotDesignSysTargetIcon =
      'assets/image/icons_not_design_sys/target_icon.png';
  static const String iconsNotDesignSysTodayExcersizeCompleteIcon =
      'assets/image/icons_not_design_sys/today_excersize_complete_icon.png';
  static const String iconsNotDesignSysWakatimeIcon =
      'assets/image/icons_not_design_sys/wakatime_icon.png';
  static const String iconsPickle = 'assets/image/icons/pickle.png';
  static const String iconsPickleFilled =
      'assets/image/icons/pickle-filled.png';
  static const String iconsPose = 'assets/image/icons/pose.png';
  static const String iconsPoseFilled = 'assets/image/icons/pose-filled.png';
  static const String iconsSearch = 'assets/image/icons/search.png';
  static const String iconsSetting = 'assets/image/icons/setting.png';
  static const String iconsShare = 'assets/image/icons/share.png';
  static const String iconsStar = 'assets/image/icons/Star.png';
  static const String iconsTag = 'assets/image/icons/tag.png';
  static const String iconsThumbUp = 'assets/image/icons/thumb-up.png';
  static const String iconsTurn = 'assets/image/icons/turn.png';
  static const String iconsTwitter = 'assets/image/icons/twitter.png';
  static const String iconsUpDownArrow = 'assets/image/icons/up-down-arrow.png';
  static const String iconsUser = 'assets/image/icons/user.png';
  static const String iconsVibration = 'assets/image/icons/vibration.png';
  static const String iconsWeight = 'assets/image/icons/weight.png';
  static const String logosGoogleLogoIcon =
      'assets/image/icons_not_design_sys/logos/google_logo_icon.png';
  static const String logosKakaoTalkLogoIcon =
      'assets/image/icons_not_design_sys/logos/kakao_talk_logo_icon.png';
  static const String logosLogo =
      'assets/image/icons_not_design_sys/logos/logo.png';
  static const String logosSplashLogo =
      'assets/image/icons_not_design_sys/logos/splash_logo.png';
  static const String logosSplashTextLogo =
      'assets/image/icons_not_design_sys/logos/splash_text_logo.png';
  static const String mediaPause = 'assets/image/icons/Media/pause.png';
  static const String mediaPlay = 'assets/image/icons/Media/Play.png';
  static const String mediaPlayFilled =
      'assets/image/icons/Media/play-filled.png';
  static const String mediaVolume = 'assets/image/icons/Media/volume.png';
  static const String mediaVolumeOff =
      'assets/image/icons/Media/Volume_Off.png';
  static const String timeAlarm = 'assets/image/icons/Time/alarm.png';
  static const String timeAlarmDel = 'assets/image/icons/Time/alarm-del.png';
  static const String timeClock = 'assets/image/icons/Time/clock.png';
  static const String timeMetronome = 'assets/image/icons/Time/metronome.png';
  static const String timeTimer = 'assets/image/icons/Time/timer.png';
}
