name: Discord Notification
on:
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: sarisia/actions-status-discord@v1
      with:
        title: "I DON'T EVER GIVE UP"
        content: "<@1154312210705821756>"
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: 000000
        image: "https://media.tenor.com/7fSQ8RYoBC0AAAAd/this-is-elon-musk.gif"
